### ISSUE TITLE
Page "Forever loading" on indexer-admin

### ISSUE THREAD

**Issue by web3cdnservices** [subquery/network-indexer-services#404]
How to reproduce:
`Log in to the indexer management page and set the current network other than Base`
![image](https://github.com/subquery/network-indexer-services/assets/115787312/967aeb86-7450-47df-b6d0-670187b48b31)

How should it work:
`The client must be notified, and either automatically or by pressing a button, must be switched to the desired network.`

**This error is only valid when the page is completely reloaded.**

@HuberTRoy

**Comment by HuberTRoy** [comment]
Fixed: https://github.com/subquery/network-indexer-services/pull/398.

But not release the changes.

You can try the dev version `subquerynetwork/indexer-coordinator-dev:v2.0.8-4`, if you want.
